name: Build/release Electron app

on:
  push:
    tags:
      - v0.0.3
jobs:
  release:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Set DEBUG
        run: echo "DEBUG=electron-builder" >> $GITHUB_ENV

      - name: Set npm_config_build_from_source
        run: echo "npm_config_build_from_source=true" >> $GITHUB_ENV

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install node-gyp globally
        run: npm install -g node-gyp@latest

      - name: Set up Python 3.11
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*-linux.AppImage
            dist/*-win-*-setup.exe
            dist/*-macos-*.dmg